In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_excel(r"D:\git\python-data-analysis-lab\datasets\resturant.xlsx")
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800.0,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800.0,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800.0,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300.0,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600.0,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [6]:
df.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [7]:
df.drop('url',inplace=True,axis=1)

In [8]:
df.isna().sum()

address                            0
name                               0
online_order                       0
book_table                         0
rate                            7775
votes                              0
phone                           1208
location                          21
rest_type                        227
dish_liked                     28078
cuisines                          45
approx_cost(for two people)      346
reviews_list                       0
menu_item                          0
listed_in(type)                    0
listed_in(city)                    0
dtype: int64

In [10]:
df['name'].iloc[4]

'Grand Village'

In [12]:
df['name'].iloc[[10,1756]]

10      CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The A...
1756     E2 - EntrÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ©e Envoy
Name: name, dtype: object

In [13]:
df['name'].iloc[1:20]

1                                        Spice Elephant
2                                       San Churro Cafe
3                                 Addhuri Udupi Bhojana
4                                         Grand Village
5                                       Timepass Dinner
6       Rosewood International Hotel - Bar & Restaurant
7                                                Onesta
8                                        Penthouse Cafe
9                                             Smacznego
10    CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The A...
11                                         Cafe Shuffle
12                                     The Coffee Shack
13                                           Caf-Eleven
14                                      San Churro Cafe
15                                        Cafe Vivacity
16                                         Catch-up-ino
17                                     Kirthi's Biryani
18                                             T3H Cafe
19                        360 Atoms Restaurant And Cafe
Name: name, dtype: object

In [14]:
import re
def clean_names(name):
    if isinstance(name, str):
        
        r = re.compile("[A-Za-z0-9\s]")
        l = re.findall(r,name)
        #return l
        j = "".join(l)
        return j
    else:
        return name
    
# Keep only: r = re.compile("[A-Za-z0-9\s]")

# A-Z     capital letters
# a-z     small letters
# 0-9     numbers
# \s      spaces

# So this pattern allows only:

# letters + numbers + spaces

#------------------------------
# l = re.findall(r, name)

# means:

# Find all allowed letters/numbers/spaces from the name and store them in a list.
# Find all characters in name that match the regex pattern r, and store them in list l.

In [15]:
res = clean_names("CafÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Down The A...")
print(res)

Caf Down The A

In [16]:
res=clean_names("E2 - EntrÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ©e Envoy")
res

'E2  Entre Envoy'

In [18]:
df.columns

Index(['address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [19]:
df.rename(columns={'reviews_list':'rating'}, inplace =True)

In [20]:
df['name']= df['name'].apply(clean_names)

In [21]:
df['name'].iloc[[10,1756]]

10      Caf Down The Alley
1756       E2  Entre Envoy
Name: name, dtype: object

In [22]:
df['rate'].value_counts()

NEW       2208
3.9/5     2098
3.8/5     2022
3.7/5     2011
3.9 /5    1874
          ...
2.2 /5       7
2.0 /5       7
2.0/5        4
1.8 /5       3
1.8/5        2
Name: rate, Length: 64, dtype: int64

In [23]:
df['rate'].unique()

array(['4.1/5', '3.8/5', '3.7/5', '3.6/5', '4.6/5', '4.0/5', '4.2/5',
       '3.9/5', '3.1/5', '3.0/5', '3.2/5', '3.3/5', '2.8/5', '4.4/5',
       '4.3/5', 'NEW', '2.9/5', '3.5/5', nan, '2.6/5', '3.8 /5', '3.4/5',
       '4.5/5', '2.5/5', '2.7/5', '4.7/5', '2.4/5', '2.2/5', '2.3/5',
       '3.4 /5', '-', '3.6 /5', '4.8/5', '3.9 /5', '4.2 /5', '4.0 /5',
       '4.1 /5', '3.7 /5', '3.1 /5', '2.9 /5', '3.3 /5', '2.8 /5',
       '3.5 /5', '2.7 /5', '2.5 /5', '3.2 /5', '2.6 /5', '4.5 /5',
       '4.3 /5', '4.4 /5', '4.9/5', '2.1/5', '2.0/5', '1.8/5', '4.6 /5',
       '4.9 /5', '3.0 /5', '4.8 /5', '2.3 /5', '4.7 /5', '2.4 /5',
       '2.1 /5', '2.2 /5', '2.0 /5', '1.8 /5'], dtype=object)

In [26]:
s='4.1/5'
s=s.split("/")[0]
s= float(s)
s

4.1

In [32]:
def clean_rate(rate):
    if rate == 'NEW' or rate == '-':
        return np.nan
    else:
        converted_rates = float(str(rate).split("/")[0])
        return converted_rates

In [33]:
res = clean_rate('4.1/5')
res

4.1

In [34]:
res = clean_rate('NEW')
res

nan

In [35]:
df['rate'] = df['rate'].apply(clean_rate)

In [36]:
df['rate'].isna().sum()

10052

In [37]:
df['rate'].mean()

3.700448817952718

In [39]:
df['rate'].fillna(round(df['rate'].mean(),1), inplace=True)

In [40]:
df.isna().sum()

address                            0
name                               0
online_order                       0
book_table                         0
rate                               0
votes                              0
phone                           1208
location                          21
rest_type                        227
dish_liked                     28078
cuisines                          45
approx_cost(for two people)      346
rating                             0
menu_item                          0
listed_in(type)                    0
listed_in(city)                    0
dtype: int64

In [41]:
df['approx_cost(for two people)'].fillna(round(df['approx_cost(for two people)'].mean(),0), inplace =True)

In [42]:
df['rest_type'] = df['rest_type'].replace(np.nan,"")

In [43]:
df['cuisines'] = df['cuisines'].replace(np.nan,"")

In [44]:
df.isna().sum()

address                            0
name                               0
online_order                       0
book_table                         0
rate                               0
votes                              0
phone                           1208
location                          21
rest_type                          0
dish_liked                     28078
cuisines                           0
approx_cost(for two people)        0
rating                             0
menu_item                          0
listed_in(type)                    0
listed_in(city)                    0
dtype: int64

In [47]:
df[df['location'].isnull()]

,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),rating,menu_item,listed_in(type),listed_in(city)
1662,"6, Abbiah Layout KC Halli Main Road, Bommanaha...",Papa Khan Rasoi,No,No,3.7,0,NaN,NaN,,NaN,,555.0,[],[],Delivery,Bannerghatta Road
9874,"6, Abbiah Layout KC Halli Main Road, Bommanaha...",Papa Khan Rasoi,No,No,3.7,0,NaN,NaN,,NaN,,555.0,[],[],Delivery,BTM
13693,"Chandapura- Anakal Main Road, Oppsite Vemana H...",Mohabbat Desi Restaurant,No,No,3.7,0,NaN,NaN,,NaN,,555.0,[],[],Delivery,Electronic City
16351,"Kudlu Gate, Bommanahalli, Bangalore",Desi Chatkara,No,No,3.7,0,NaN,NaN,,NaN,,555.0,[],[],Delivery,HSR
26432,"IB Road, Lorry Stand, Kushaal Nagar, Ward 10, ...",New Taj Biryani Centre,No,No,3.7,0,NaN,NaN,,NaN,,555.0,[],[],Dine-out,Kammanahalli
26519,"Koramangala 8th Block, Bangalore",ABs Absolute Barbecues,No,No,3.7,0,NaN,NaN,,NaN,,555.0,[],[],Buffet,Koramangala 4th Block
27672,"6, Kathalipalya Village, 6th Cross, Koramangal...",Manchow,No,No,3.7,0,NaN,NaN,,NaN,,555.0,[],[],Delivery,Koramangala 4th Block
28611,"6, Kathalipalya Village, 6th Cross, Koramangal...",Manchow,No,No,3.7,0,NaN,NaN,,NaN,,555.0,[],[],Dine-out,Koramangala 4th Block
29298,"Koramangala 8th Block, Bangalore",ABs Absolute Barbecues,No,No,3.7,0,NaN,NaN,,NaN,,555.0,[],[],Buffet,Koramangala 5th Block
30604,"6, Kathalipalya Village, 6th Cross, Koramangal...",Manchow,No,No,3.7,0,NaN,NaN,,NaN,,555.0,[],[],Delivery,Koramangala 5th Block
31400,"6, Kathalipalya Village, 6th Cross, Koramangal...",Manchow,No,No,3.7,0,NaN,NaN,,NaN,,555.0,[],[],Dine-out,Koramangala 5th Block
32131,"Koramangala 8th Block, Bangalore",ABs Absolute Barbecues,No,No,3.7,0,NaN,NaN,,NaN,,555.0,[],[],Buffet,Koramangala 6th Block
33457,"80 Feet Road, Koramangala 4th Block, Bangalore",La Lunch Box,No,No,3.7,0,NaN,NaN,,NaN,,555.0,[],[],Delivery,Koramangala 6th Block
34755,"Koramangala 8th Block, Bangalore",ABs Absolute Barbecues,No,No,3.7,0,NaN,NaN,,NaN,,555.0,[],[],Buffet,Koramangala 7th Block
40354,"399/34, 19th Main, Near Navarang Theatre, 2nd ...",The Happy Vegetarian,No,No,3.7,0,NaN,NaN,,NaN,,555.0,[],[],Dine-out,Malleshwaram
40556,"1630, 6th Main Road, AECS Layout E Block, Mara...",Risalo Restaurant,No,No,3.7,0,NaN,NaN,,NaN,,555.0,[],[],Cafes,Marathahalli
41980,"1630, 6th Main Road, AECS Layout E Block, Mara...",Risalo Restaurant,No,No,3.7,0,NaN,NaN,,NaN,,555.0,[],[],Dine-out,Marathahalli
46586,"9, Magadi Main Road, Cholourpalya, Vijay Nagar",The Cinema,No,No,3.7,0,NaN,NaN,,NaN,,555.0,[],[],Delivery,Rajajinagar
46609,"West of Chord Road, Govindaraja Nagar, Below H...",Grill Biryanis,No,No,3.7,0,NaN,NaN,,NaN,,555.0,[],[],Delivery,Rajajinagar
46752,"399/34, 19th Main, Near Navarang Theatre, 2nd ...",The Happy Vegetarian,No,No,3.7,0,NaN,NaN,,NaN,,555.0,[],[],Dine-out,Rajajinagar
47134,"9, Magadi Main Road, Cholourpalya, Vijay Nagar",The Cinema,No,No,3.7,0,NaN,NaN,,NaN,,555.0,[],[],Dine-out,Rajajinagar

In [48]:
df['location'] = df['location'].replace(np.nan, "")

In [49]:
df.isna().sum()

address                            0
name                               0
online_order                       0
book_table                         0
rate                               0
votes                              0
phone                           1208
location                           0
rest_type                          0
dish_liked                     28078
cuisines                           0
approx_cost(for two people)        0
rating                             0
menu_item                          0
listed_in(type)                    0
listed_in(city)                    0
dtype: int64

In [50]:
df.drop(["address","listed_in(type)"],inplace=True, axis=1)

In [51]:
df.rename(columns={"phone":"contact"},inplace=True)

In [52]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'contact',
       'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'rating', 'menu_item',
       'listed_in(city)'],
      dtype='object')